### PR TITLE
Fix firebase warnings.

### PR DESCRIPTION
**Pull request by Undeadlol1**
In Android on Windows there a constant Firebase warning which usually results in "v8 is out of memory" error.
Image 274
 
Image 275

This workaround doesn't solve the issue completely but it removes the warnings and crashes occur much-much less frequently.

Image 276

See the firebase issue for more info:
https://github.com/firebase/firebase-js-sdk/issues/97

### CODE REVIEW

**Comment by elolelo** [comment]
Have you tried to use line: console.disableYellowBox = true;
Although it does not solve the issue completely, it does remove the warnings (at least it did to mine)

**Comment by Undeadlol1** [comment]
Disabling all warnings is not a great decision. It might come back and bite you in the future.

**Comment by elolelo** [comment]
https://stackoverflow.com/a/46678121

> Disabling all warnings is not a great decision. It might come back and bite you in the future.

>They might come back ... how about this link https://stackoverflow.com/a/46678121 ?

**Comment by Undeadlol1** [comment]
> They might come back ... how about this link https://stackoverflow.com/a/46678121 ?

This is pretty much what my PR does.

**Comment by elolelo** [comment]
> > They might come back ... how about this link https://stackoverflow.com/a/46678121 ?
> 
> This is pretty much what my PR does.

Are you saying your PR did this?         did it work?      I am facing the same issue these yellow issues too . This stackoverflow didn't work for me -   did it work for you or your PR?

**Comment by Undeadlol1** [comment]
Yes, PR removes the yellow box.

**Comment by mcnamee** [comment]
Hi @Undeadlol1 
I understand why you've done this. Can you separate the specifics into a separate module/file (perhaps call it something like /src/lib/firebase-fix.js or something similar) so that it's separated and easily removed (if/when Firebase is fixed)?

**Pull request closed without merging**
