### PR TITLE
Rematch integration

### PR DESCRIPTION
**Pull request by ealemda2**
#### Added [Rematch](https://github.com/rematch/rematch) to the project. 

You can now use [models](https://github.com/rematch/rematch#step-2-models) that combine actions, action creators, state, and reducers in one place. I added a basic example under `src/models/example.js`.

Existing Redux stuff still works since Rematch is build on top of Redux. Hope this is somewhat helpful and allows for an easier development process.

### CODE REVIEW

**Comment by mcnamee** [comment]
@ealemda2 - I like the consolidation and simplicity, great work!

Are you interested in completing the integration with members and recipes?

Also in regards to testing - has this been tested in both native (iOS/Android) and web?

**Comment by ealemda2** [comment]
Both members and recipes should be working as they're imported into the store `import reducers from '../reducers';`. 

It's been tested on iOS (iPhone X - 12.1) and Android (Pixel 2 - 9.0) simulators and web. I also tested it on my iPhone physically but don't have an access to an actual Android device at the moment.

**Comment by ealemda2** [comment]
Oh you mean converting the reducers etc. for members and recipes into their own models. I left them as they were to show that you can use a combination of existing redux stuff with new models. I can convert them if necessary though.

**Comment by mcnamee** [comment]
Hi @ealemda2 
Got it. For clarity and to prescribe a single 'standard' way of redux implementation (which is helpful for boilerplates) - it'd be great to convert all existing 'models' to the rematch way.

**Comment by ealemda2** [comment]
I migrated the reducers and actions to Rematch models. Updated some docs to reflect it as well. Works fine on web, iOS and Android simulators. Let me know what you think and if there's anything I missed.

**Comment by mcnamee** [comment]
Really good job @ealemda2 

Few minor things I picked up before a merge:

- [ ] React Native Debugger or Redux Devtools - I couldn't get these working with the latest - I suspect it's because it's [lacking this](https://github.com/mcnamee/react-native-starter-kit/blob/master/src/store/index.js#L16)
- [ ] The `redux-logger` you've implemented is fine - however it shouldn't be bundled for web production AND shouldn't run for React Native (it only buries the console in difficult to read text)
- [ ] Does `src/containers/UpdateProfile.js` use the `getUserData` function (if not let's remove
)?
- [ ] Is `store/recipes` still needed? Previously, before recipes had loaded content from the API, it'd show the 'shadow content' seend in this file - kind of a usability nicety.
- [ ] Various files need linting to be of consistent code style - [here's more details](https://github.com/mcnamee/react-native-starter-kit/blob/master/docs/testing.md#linting-with-eslint) if you don't have it in your IDE

**Comment by ealemda2** [comment]
@mcnamee Thanks for looking over it. I'll let you know when I've gotten around to making the minor fixes.

**Comment by ealemda2** [comment]
@mcnamee, I committed the fixes for the issues above!

As for using Redux DevTools with React Native Debugger, I had no problem running the RN Debugger on port 19001 and seeing the Redux state after clicking "Debug JS Remotely" from the Expo menu on the iOS or Android simulators while the RN Debugger is connected at 19001. 

I remember having to delete the Expo app and run `expo r -c` when I had an issue with the Redux devtools before as well.

**Comment by mcnamee** [comment]
You're a legend @ealemda2 - great job!

**Pull request merged**
